unique_ids:
  assets:
    standard-page.html: KLFQL2I2NF3JTK4OEROBZMAMKPNY55VN
    theme.css: 2XFTMMEAXY6ZAQV7TQQ5XCOU3HWLY26B
  forms:
    Form1: Y7IMFGYITDQ77EXNFCH6LH3FKG3ZTORQ
  modules: {}
  scripts: {}
  server_modules: {}
